// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhfdnblzjuenhttnlkka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoZmRuYmx6anVlbmh0dG5sa2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjk0NzIsImV4cCI6MjA3MDY0NTQ3Mn0.LuSpWIXHpRl5aKlqEiV965Q8tGLI9yijfp9qAsJy7aA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});